server:
  port: 8090

spring:
  application:
    name: msvc-student
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/GestionTareas
    username: root
    password: 271631126
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

security:
  jwt:
    key:
      private: 8b575f54e3d16cec96df1ab19cb3a01cd6ec1e78c511e495a11e25fb61948efc
    user:
      generator: JjersaR-BACKEND

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
