server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  # el gateway estara activo
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user
          uri: http://msvc-user:8090
          predicates:
            - Path=/api/user/**
        - id: project
          uri: http://msvc-project:8091
          predicates:
            - Path=/api/project/**
        - id: task
          uri: http://msvc-task:8092
          predicates:
            - Path=/api/task/**

eureka:
  client:
    register-with-ureka: false
