spring:
  application:
    name: msvc-eureka

server:
  port: 8761 # puerto por defecto de eureka

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    server-url:
      defaultZone: http://msvc-eureka:${server.port}/eureka
