server:
  port: 8091

spring:
  application:
    name: msvc-project
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://gestiontareasBD:3306/GestionTareas?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 271631126
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://msvc-eureka:8761/eureka
